resources:
- repo: self
  clean: true

pool:
  vmImage: 'vs2017-win2016'

variables:
- group: 'GitHub PersonalAccessToken Code (Read)'
- name: buildConfiguration
  value: 'Release'
  
steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
    publishTestResults: true

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    projects: '**/AzureDurableFunctionsDemo1.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.ArtifactStagingDirectory)'
    zipAfterPublish: true
    publishWebProjects: false

- task: PowerShell@2
  displayName: Git clone TerraformModules repo
  inputs:
    targetType: inline
    script: git clone https://$(PersonalAccessToken)@github.com/markgossa/HashiTalk1-TerraformModules.git --branch develop --single-branch --verbose $(Build.Repository.LocalPath)\Deployment\Terraform\TerraformModules

- task: CmdLine@2
  displayName: Terraform Install
  inputs:
    script: choco install terraform

- task: CmdLine@2
  displayName: Terraform Init
  inputs:
    script: terraform init -input=false -backend=false deployment\terraform

- task: CmdLine@2
  displayName: Terraform Validate (DEV)
  inputs:
    script: terraform validate -var-file="deployment\terraform\envDev.tfvars" -var client_id=test -var client_secret=test -var tenant_id=test -var subscription_id=test -var FunctionAppName=test deployment\terraform

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts: App'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'app'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts: Terraform'
  inputs:
    pathtoPublish: 'deployment\terraform'
    ArtifactName: 'terraform'
